### ISSUE TITLE
专门回来star一下，之前自己弄的不能HDMI，但是讲PPT有时候需要投屏

### ISSUE THREAD

**Issue by RebornL1** [Erf172/Lenovo_XiaoXin_Rui7000_Hackintosh#4]
我想知道，大佬是让独显工作了吗，我发现我居然可以HDMI连接我的4k屏幕

**Comment by Erf172** [comment]
独显驱动不了的。小新的HDMI走的是核显。独显我给屏蔽了

**Comment by RebornL1** [comment]
这样啊，我还以为一个核显驱动不起来一块4k屏和笔记本的屏幕呢😆
    	
    	

    	Re_bornLi
    
  




On Fri, May 24, 2019 at 9:02 AM +0800, "Erf172" <notifications@github.com> wrote:












独显驱动不了的。小新的HDMI走的是核显。独显我给屏蔽了
