### ISSUE TITLE
MacOS catalina更新

### ISSUE THREAD

**Issue by RebornL1** [Erf172/Lenovo_XiaoXin_Rui7000_Hackintosh#6]
## 期待老哥可以早日支持Catalina

**Comment by xoomp** [comment]
我提交了pull request，等不及可以试试我的fork，精简更新了一些驱动，每日使用很稳定

**Comment by RebornL1** [comment]
老哥，我系统是装好了，可是我发现没有蓝牙模块了

**Comment by RebornL1** [comment]
![image](https://user-images.githubusercontent.com/47822567/68079920-bd552200-fe2c-11e9-9e30-6c88afe7cc65.png)
我准备试一下看这个能解决问题不，还有就是我发现如果给磁盘设置密码好像clover就不能引导系统了

**Comment by xoomp** [comment]
抱歉刚看到，您先试试，最近没有用到蓝牙竟然都不知道，一看确实有问题。

**Comment by RebornL1** [comment]
我用图上给的进行操作已经好使了，就是若系统扇区前还有apfs的空间可能会导致clover找不到系统的情况，我的处理方法就是变成了一整块apfs
